/**
 * The frozen moment, typed.
 *
 * WHAT THIS FILE IS FOR. `snapshot.json` is generated by `npm run snapshot` straight out of
 * the database and is the only source of numbers the walkthrough has. This module gives it
 * a shape the compiler understands, so a scene that reads a field which stopped being
 * produced fails at build time rather than rendering the word `undefined` on a projector.
 *
 * THE WALKTHROUGH NEVER FETCHES. It is shown to a room, often on a laptop that is not on
 * the office network, and a request that fails mid-presentation has no recovery. Everything
 * is captured once and committed.
 *
 * THE MOMENT: chiller 1, condenser fouling, 7 June 2037. Health 62 of 100, an excess of
 * 1.151 K against a threshold of 3.0 K, and the remaining-life estimate REFUSED for want of
 * samples — the real estimate arrives two days later. See the long note in
 * web/scripts/make-snapshot.ts for why that day was chosen over a tidier one.
 */

import data from "./snapshot.json";

export interface Reading {
  t: string;
  v: number;
}

export interface Snapshot {
  /** When the capture was taken — not the moment being shown. */
  generatedAt: string;
  /** The moment being shown, as a plain date. */
  at: string;
  source: string;

  asset: {
    asset_id: string;
    name: string;
    brick_class: string;
    replacement_cost_usd: number | null;
  };

  /** The instrument the walkthrough follows from end to end. */
  point: {
    point_id: string;
    name: string;
    unit_si: string;
    expected_min: number;
    expected_max: number;
  };

  /** Counted in the opening scene: how many instruments, and how many already broken. */
  instruments: {
    total: number;
    unusable: number;
    reasons: readonly string[];
  };

  commissioning: { days: number; from: string; to: string };

  /** Hourly history, oldest first. The tail the travelling reading drags behind it. */
  series: readonly Reading[];
  /** The one reading the whole walkthrough follows. */
  reading: Reading;

  /** What the machine should have been producing, and by how much it missed. */
  baseline: {
    residuals: readonly {
      t: string;
      observed: number;
      expected: number;
      residual: number;
    }[];
  };

  mode: {
    mode_id: string;
    mode_name: string;
    failure_threshold: number;
    indicator_unit: string;
    penalty_kw_per_unit: number;
    degradation_process: string;
    threshold_rationale: string;
  };

  indicator: {
    threshold: number;
    unit: string;
    /** The written physical justification for the threshold, straight out of the table. */
    rationale: string;
    /** How the fault accumulates — `gamma` means it only ever gets worse. */
    process: string;
    penaltyKwPerUnit: number;
  };

  health: {
    value: number;
    excess: number;
    raw: number;
    onset: string | null;
    /** The sum, written out, so the screen can show the arithmetic rather than assert it. */
    arithmetic: string;
    daily: readonly { t: string; health: number; raw: number; monotonic: number }[];
  };

  /**
   * Either a published estimate or a refusal carrying its reason. The refusal is not an
   * error state — it is one of the things this platform exists to be able to say.
   */
  prediction:
    | {
        kind: "estimate";
        as_of: string;
        p10: number;
        p50: number;
        p90: number;
        n_samples: number;
      }
    | {
        kind: "refusal";
        reason: string;
        /** When the system did finally have enough evidence to answer. */
        arrivesAt: string | null;
        arrivingEstimate: {
          as_of: string;
          p10: number;
          p50: number;
          p90: number;
          n_samples: number;
        } | null;
      };

  advisory: {
    advisory_id: string;
    fault_id: string;
    fault_class: string;
    status: string;
    health: number;
    severity: number;
    priority: number | null;
    cost_usd: number | null;
    effort_usd: number | null;
    consequential: boolean;
    cause_asset: string | null;
    cause_fault: string | null;
    detail: unknown;
  } | null;

  /** Other machines being worked on at the same moment, for showing parallel work. */
  others: readonly {
    asset_id: string;
    name: string;
    mode_id: string;
    health: number;
  }[];
}

export const SNAPSHOT = data as unknown as Snapshot;
