"""Render VALIDATION.md from computed metrics. No number in this file is a literal.

The document is generated on every run and overwritten in place. That is a rule with
a reason behind it: a validation document with hand-written numbers in it decays
silently, and the moment one figure in it is stale the whole document is worthless
because a reader cannot tell which one. Every quantity below arrives as an argument.
The prose is fixed and the numbers are not, so a regression shows up as a changed
number under unchanged prose rather than as a document nobody dares regenerate.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from validation.attribution import (
    CLASSES,
    ClassOutcome,
    SuppressionCase,
    class_matrix,
    majority_baseline,
)
from validation.detect import RULES_ONLY, Sweep
from validation.groundtruth import FaultEvent, ScenarioLabel, SeverityWindow
from validation.metrics import (
    EXCLUDED_SCENARIOS,
    Confusion,
    EventOutcome,
    FalseAlarms,
    FalsePositiveSource,
    HeldOut,
    LeadSummary,
    LeadTime,
)
from validation.prognostics import (
    ALPHA,
    AlphaLambdaPoint,
    AlphaLambdaRollUp,
    Calibration,
    CoverageRollUp,
)

REPO_ROOT = Path(__file__).resolve().parents[1]


HEADER = """# Validation

> **Generated by `validation/harness.py` on {generated}. Do not edit by hand.**
> Every number in this document is recomputed from the database and the answer key on
> each run and the file is overwritten in place. Regenerate with `make validate`.

The labels these results are scored against were not created by this project. The
fault signatures come from the LBNL Fault Detection and Diagnostics Datasets, a public
release produced by a consortium of LBNL, PNNL, NREL, ORNL and Drexel, in which each
fault is simulated at several measured severities alongside a fault-free reference
run. What this project synthesised is the trajectory BETWEEN those measured
severities, because no public run-to-failure dataset exists for building HVAC
equipment. The answer key therefore holds two kinds of fact: which fault was injected
into which machine, which is LBNL's, and when it passed each severity rung, which is
this project's.

The separation is enforced by the database rather than by discipline. Every layer that
detects, scores, baselines, predicts or diagnoses connects as a role with no access
whatsoever to schema `groundtruth` -- not restricted access, none -- and the answer key
is opened by exactly one module, `validation/groundtruth.py`, under a different
credential. No detector in this project can have seen the label it is scored against.

**What was evaluated.** {windows} windows spanning {span_from} to {span_to}.
{observed:,} asset-days hold readings; of those, {scored:,} are days on which at least
one detector was willing to judge the machine, and only those can appear in a table
below. {findings} findings were raised across every detector.

The gap between those two counts is not rounding. The rules decline to evaluate an
air handler while the building is unoccupied, and decline to evaluate a chiller that
is not running, for an hour after it starts, and at any instant below a minimum load.
One of the three chillers in this plant runs about one percent of the year. Counting
its idle days as days it was correctly found healthy would have added hundreds of free
true negatives to every table below and quietly divided the false-alarm rate.
"""

WHY_FALSE_ALARMS = """
## 1. False alarms per asset-day

**This is the first number in this document on purpose.** Automated fault detection in
buildings does not usually fail by missing faults. It fails by crying wolf: the
detection works, the operator is interrupted several times a day by findings that turn
out to be a warm afternoon or a scheduled setpoint change, and within a month nobody
opens the screen again. A system with perfect recall and one spurious finding per
machine per day has trained the person it was bought for to ignore it, and is worth
less than no system at all. So the rate on equipment that was working comes before any
claim about equipment that was not.

Counted over asset-days labelled healthy: the two synthesised fault-free runs, the
LBNL fault-free reference year, and the pre-injection stretch of every faulted run.
Pre-injection days are ordinary healthy days here, including the three weeks the
baselines are fitted on -- a finding raised while the equipment was still healthy is a
false alarm whatever else was happening that week.

Three counts, because they answer different questions:

- **findings per asset-day** is the headline. A finding is one (machine, fault) pair
  raised once, however many separate episodes it covered -- the unit an operator
  disposes of. Nine afternoons of the same saturated valve is one finding, not nine.
- **alarm-days** is the share of healthy days with at least one finding standing. It
  is exactly the false-positive count in section 2's confusion matrix, so the two
  sections cannot disagree.
- **episodes** is the raw count of sustained stretches, carried only so these figures
  line up against the per-rule tables produced in checkpoints 3.3 and 3.4.
"""

WHY_SEVERITY_ONE = """
## 2. Detection at severity level 1

### Why every accuracy figure here is restricted to level 1

LBNL publishes each fault at several measured severities. Condenser fouling comes at
95% and 65% of heat transfer retained; bypass leakage at 25%, 50% and 75%; the damper
stuck at 10%, 25% and 75% open. **Detecting the severe end of that range is not
evidence that a fault detection system works.** A condenser down to 65% of its heat
transfer moves the approach temperature and the kilowatts per ton so far outside
anything weather can explain that a fixed threshold set by hand would catch it. The
severe cases are the ones any system catches, and an accuracy figure computed over a
whole trajectory is dominated by them.

Severity level 1 is the opposite case. It is the mildest condition LBNL measured for
that fault -- a valve leaking slightly, 5% of heat transfer lost -- and its effect on
every signal is of the same order as the effect of the outdoor air temperature being a
few degrees higher than yesterday. Separating it from normal operation is the whole
problem. It is also the only case where a warning is worth anything, because by the
time the fault reaches its terminal severity the energy has already been spent.

So the severity-1 window of each run is reconstructed by replaying the same seeded
trajectory the simulator built the run from, and it closes the moment the trajectory
reaches the SECOND measured rung. Every asset-day after that is excluded from the
figures below rather than counted as an easy win.

### What counts as a detection

A detection is a claim about a MACHINE on a DAY: the platform told an operator
something was wrong with this unit today. Any of the nine physics-derived rules, or
any failure mode whose degradation the changepoint detector confirmed, counts.

Two things follow, and both cut against the numbers rather than for them. The rule
firings are re-run from the measurements here rather than read from a table, because
nothing persists them. The degradation detections are also re-run, for a subtler
reason: `app.health_state` stores the changepoint detector's ESTIMATED onset -- the
retrospective "this began on the 3rd" -- and an operator learned nothing on the 3rd.
They learned when the cumulative-sum statistic crossed its decision interval, which is
days later and is written down nowhere. Scoring against the estimated onset would
credit this system with warning it never gave, so the health layer is recomputed and
the confirmation instant is used.

The claim is also deliberately generous in one direction, stated plainly: it is
asset-level, so a run is credited when ANY channel fires on the faulted machine, not
only when the correct fault is named. During condenser fouling the efficiency-loss mode
firing is physically the same fault seen from another angle and crediting it is fair;
during sensor drift, a mode firing for an unrelated reason would also be credited and
that is not. Whether the right fault was NAMED is a separate question and these figures
do not answer it.
"""

WHY_LEAD_TIME = """
## 3. Lead time

The gap between the first warning and the failure is what this system is for.
Detecting a fault the week the equipment stops is a report, not a prediction.

The population is one row per (injected fault, detection channel), not one row per
fault. That is what makes a distribution out of a handful of events: condenser fouling
is caught by the approach-temperature rule, by the kilowatt-per-ton rule, and by two
separate degradation modes, and those warnings arrive on four different days. Quoting
only the earliest would describe a system that always warns as early as its luckiest
detector. The **tenth percentile is the number to read** -- nine warnings in ten
arrived at least this far ahead -- and the median is the typical case.

Failure here means the injected fault reaching its terminal severity, which is the
answer key's `t_failure`. That is not the same event as the indicator crossing the
physically justified threshold the remaining-life model predicts, and the two dates can
differ by weeks -- an important distinction, because it means a lead time measured here
and a remaining-life error are answers to two different questions.
"""


def table(headers: list[str], rows: list[list[str]], align: str = "") -> str:
    """A GitHub-flavoured markdown table. `align` is one of l, r, c per column."""
    align = align or "l" * len(headers)
    rule = {"l": ":---", "r": "---:", "c": ":---:"}
    out = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(rule[a] for a in align) + " |",
    ]
    out += ["| " + " | ".join(row) + " |" for row in rows]
    return "\n".join(out)


def pct(value: float | None, digits: int = 1) -> str:
    return "n/a" if value is None else f"{value * 100:.{digits}f}%"


def num(value: float | None, digits: int = 1) -> str:
    return "n/a" if value is None else f"{value:.{digits}f}"


def render(
    generated: datetime,
    labels: dict[str, ScenarioLabel],
    events: list[FaultEvent],
    severity_windows: dict[str, SeverityWindow],
    sweep: Sweep,
    span: tuple[str, str],
    alarms: list[FalseAlarms],
    matrix: Confusion,
    outcomes: list[EventOutcome],
    leads: list[LeadTime],
    summaries: list[LeadSummary],
    late: list[tuple[str, str, str, float]],
    heldout: list[HeldOut],
    sources: list[FalsePositiveSource],
    calibrations: list[Calibration],
    coverage: list[CoverageRollUp],
    unscoreable: list[tuple[str, int, str]],
    total_estimates: int,
    alpha_points: list[AlphaLambdaPoint],
    alpha_all: list[AlphaLambdaRollUp],
    alpha_matched: list[AlphaLambdaRollUp],
    figure: Path | None,
    class_outcomes: list[ClassOutcome],
    suppression: list[SuppressionCase],
    grid_check: list[tuple[str, int, int]],
) -> str:
    """The whole document."""
    parts = [
        HEADER.format(
            generated=generated.strftime("%Y-%m-%d %H:%M:%S %Z"),
            windows=len(sweep.scored),
            observed=sweep.observed_asset_days,
            scored=sweep.scored_asset_days,
            findings=len(sweep.findings),
            span_from=span[0],
            span_to=span[1],
        ),
        _section_false_alarms(alarms),
        _section_detection(
            matrix, outcomes, severity_windows, labels, events, sources, sweep
        ),
        _section_lead_time(summaries, leads, late),
        _section_held_out(heldout),
        _section_calibration(
            calibrations, coverage, unscoreable, total_estimates
        ),
        _section_alpha_lambda(alpha_all, alpha_matched, alpha_points, figure),
        _section_fault_class(class_outcomes),
        _section_suppression(suppression),
        _section_method(severity_windows, grid_check, sweep),
    ]
    return "\n".join(parts).rstrip() + "\n"


def _section_false_alarms(alarms: list[FalseAlarms]) -> str:
    rows = []
    total_days = total_findings = total_alarm_days = total_episodes = 0
    for entry in sorted(alarms, key=lambda a: -a.asset_days):
        rows.append([
            f"`{entry.scenario_id}`",
            f"{entry.asset_days:,}",
            str(entry.findings),
            f"**{entry.findings_per_asset_day:.4f}**",
            f"{entry.alarm_days:,} ({pct(entry.alarm_day_fraction)})",
            str(entry.episodes),
            entry.detectors,
        ])
        total_days += entry.asset_days
        total_findings += entry.findings
        total_alarm_days += entry.alarm_days
        total_episodes += entry.episodes
    rate = total_findings / total_days if total_days else 0.0
    rows.append([
        "**ALL HEALTHY ASSET-DAYS**",
        f"**{total_days:,}**",
        f"**{total_findings}**",
        f"**{rate:.4f}**",
        f"**{total_alarm_days:,}**",
        f"**{total_episodes}**",
        "",
    ])
    body = table(
        ["run", "healthy asset-days", "findings", "findings per asset-day",
         "alarm-days", "episodes", "detectors evaluated"],
        rows,
        align="lrrrrrl",
    )
    headline = (
        f"\n**{rate:.4f} findings per healthy asset-day** across {total_days:,} "
        f"asset-days of equipment that was working: one finding every "
        f"{1.0 / rate:,.0f} asset-days.\n"
        if rate > 0 else
        f"\n**Zero findings across {total_days:,} healthy asset-days.**\n"
    )
    return WHY_FALSE_ALARMS + "\n" + body + "\n" + headline


def _section_detection(
    matrix: Confusion,
    outcomes: list[EventOutcome],
    severity_windows: dict[str, SeverityWindow],
    labels: dict[str, ScenarioLabel],
    events: list[FaultEvent],
    sources: list[FalsePositiveSource],
    sweep: Sweep,
) -> str:
    scored = matrix.tp + matrix.fp + matrix.fn + matrix.tn
    unlabelled = sweep.scored_asset_days - scored
    confusion_table = table(
        ["", "platform flagged the machine", "platform said nothing"],
        [
            ["**fault present, at level 1**", f"**{matrix.tp:,}** true positive",
             f"{matrix.fn:,} false negative"],
            ["**equipment healthy**", f"{matrix.fp:,} false positive",
             f"{matrix.tn:,} true negative"],
        ],
        align="lrr",
    )
    headline = table(
        ["metric", "value", "reading"],
        [
            ["**precision**", f"**{pct(matrix.precision, 1)}**",
             "of the days we raised something, this share had a real fault"],
            ["**recall**", f"**{pct(matrix.recall, 1)}**",
             "of the days a mild fault was present, this share was flagged"],
            ["**F1**", f"**{num(matrix.f1, 3)}**", "harmonic mean of the two"],
        ],
        align="lrl",
    )

    event_rows = []
    for outcome in outcomes:
        event_rows.append([
            f"`{outcome.scenario_id}`",
            outcome.asset_id,
            f"`{outcome.fault_mode}`",
            outcome.mildest_label,
            f"{outcome.window_days:.1f}",
            "**yes**" if outcome.caught else "**NO**",
            num(outcome.days_after_injection) if outcome.caught else "-",
            outcome.first_channel or "-",
            f"{outcome.detected_days}/{outcome.positive_days} ({pct(outcome.coverage, 0)})",
        ])
    event_table = table(
        ["run", "machine", "injected fault", "LBNL's mildest measured case",
         "level-1 window, days", "caught at level 1", "days to first warning",
         "which channel fired first", "level-1 days flagged"],
        event_rows,
        align="lllllcrlr",
    )

    excluded_rows = []
    for scenario_id, reason in sorted(EXCLUDED_SCENARIOS.items()):
        excluded_rows.append([f"`{scenario_id}`", reason])
    for scenario_id, window in sorted(severity_windows.items()):
        label = labels.get(scenario_id)
        if window.scored or (label is not None and label.is_fault_free):
            continue
        if scenario_id in EXCLUDED_SCENARIOS:
            continue
        excluded_rows.append([f"`{scenario_id}`", window.reason])
    excluded = table(["run", "why it is not in the figures above"], excluded_rows)

    caught = sum(1 for o in outcomes if o.caught)
    return (
        WHY_SEVERITY_ONE
        + f"\n### Confusion over {scored:,} labelled asset-days\n\n"
        + f"A further {unlabelled:,} asset-days were judged by a detector but carry no "
          f"label: the fault was present and had already passed level 1. They appear in "
          f"neither row.\n\n"
        + confusion_table + "\n\n" + headline
        + _false_positive_note(matrix, sources, sweep)
        + f"\n### Per injected fault\n\n{caught} of {len(outcomes)} injected faults "
          f"were caught while still at severity level 1.\n\n"
        + event_table
        + "\n\n### Runs excluded from these figures, and why\n\n"
        + excluded + "\n"
        + f"\n{len(events)} faults are recorded in the answer key in total. The "
          f"held-out one is reported on its own in section 4.\n"
    )


def _false_positive_note(
    matrix: Confusion, sources: list[FalsePositiveSource], sweep: Sweep
) -> str:
    """Where the false positives came from. Precision without this is not usable."""
    if not sources:
        return (
            f"\n### Where the false positives came from\n\nThere were none: not one "
            f"finding stood on a healthy asset-day across all {matrix.tn:,} of them.\n"
        )
    rows = [
        [
            f"`{entry.scenario_id}`", entry.asset_id, f"`{entry.fault_id}`",
            entry.source.replace("_", " "), f"{entry.fp_days:,}",
            pct(entry.fp_days / matrix.fp if matrix.fp else 0.0, 0),
            ("**yes** — " + ", ".join(f"{d:%Y-%m-%d}" for d in entry.calendar_twins)
             if entry.calendar_twins else "no"),
        ]
        for entry in sources
    ]
    total_findings = len(sweep.findings)
    worst = sources[0]
    share = worst.fp_days / matrix.fp if matrix.fp else 0.0
    points = worst.health_points_lost
    return f"""

### Where the false positives came from

{table(["run", "machine", "channel", "detector", "false-positive asset-days",
        "share of all false positives", "same channel, same day of year, another run?"],
       rows, align="llllrrl")}

**{len(sources)} distinct false findings, out of {total_findings} findings raised in
total**, and between them they stood for {matrix.fp} healthy asset-days. Those are the
same result counted two ways and both are worth having: the platform put
{len(sources)} wrong item{"" if len(sources) == 1 else "s"} in front of an operator, and
each then sat on the screen for two months afterwards. Precision is computed per
asset-day, so it is the second framing that drags it to {pct(matrix.precision)}. Counted
as findings instead, {len(sources)} of {total_findings} were raised on a machine with
nothing wrong with it.

`{worst.fault_id}` on `{worst.asset_id}` alone is {pct(share, 0)} of the false-positive
total. Its detail: {worst.detail}. So the whole finding is a confirmed change costing
{points} health point{"" if points == 1 else "s"} out of a hundred -- and the rightmost
column above is the more damning part of it. That channel raises the same finding on the
same machine on the same day of the year across several runs, faulted and fault-free
alike. Every run reads the same 2018 source data shifted by whole years, so a detection
repeating on the same calendar day is responding to something in the weather and load of
that week rather than to the condition of the machine. What exactly, these measurements
do not establish -- the indicator's mean over the fault-free run is within 0.01 of zero,
so it is not a steady seasonal drift, and identifying the mechanism belongs with the
indicator rather than with the harness.

It is a real false positive and it would reach an operator. It would arrive at the bottom
of the queue rather than as an alarm -- {points} health point{"" if points == 1 else "s"}
produces almost no severity and almost no cost of inaction -- which is what the ranking in
the advisory layer is for. But ranking it low is not the same as being right about it, and
this is the clearest defect these measurements expose.
"""


def _section_lead_time(
    summaries: list[LeadSummary],
    leads: list[LeadTime],
    late: list[tuple[str, str, str, float]],
) -> str:
    rows = []
    for entry in summaries:
        bold = entry.fault_mode.startswith("ALL")
        wrap = (lambda s: f"**{s}**") if bold else (lambda s: s)
        rows.append([
            wrap(f"`{entry.fault_mode}`" if not bold else entry.fault_mode),
            wrap(str(entry.n)),
            wrap(f"{entry.median:.1f}"),
            wrap(f"{entry.p10:.1f}"),
            wrap(f"{entry.minimum:.1f}"),
            wrap(f"{entry.maximum:.1f}"),
            wrap(entry.earliest_channel),
        ])
    summary_table = table(
        ["injected fault", "warnings", "median lead, days",
         "10th percentile, days", "worst", "best", "earliest channel"],
        rows,
        align="lrrrrrl",
    )

    detail_rows = [
        [
            f"`{lead.scenario_id}`", lead.asset_id, lead.source.replace("_", " "),
            f"`{lead.fault_id}`", f"{lead.first_seen:%Y-%m-%d}",
            f"{lead.t_failure:%Y-%m-%d}", f"**{lead.lead_days:.1f}**",
        ]
        for lead in leads
    ]
    detail = table(
        ["run", "machine", "detector", "channel", "first warning",
         "terminal severity reached", "lead, days"],
        detail_rows,
        align="llllllr",
    )

    late_note = ""
    if late:
        late_rows = [
            [f"`{scenario}`", asset, f"`{fault}`", f"{delay:.1f}"]
            for scenario, asset, fault, delay in late
        ]
        late_note = (
            "\n### Findings that were not warnings\n\n"
            "Raised only after the injected fault had already reached terminal "
            "severity, so they carry no lead and are excluded from the distribution "
            "above rather than averaged into it.\n\n"
            + table(
                ["run", "machine", "channel", "days after terminal severity"],
                late_rows,
                align="lllr",
            )
            + "\n"
        )

    return (
        WHY_LEAD_TIME
        + "\n" + summary_table
        + "\n\n### Every warning, individually\n\n" + detail + "\n"
        + late_note
    )


def _section_held_out(heldout: list[HeldOut]) -> str:
    """The cooling tower fault, and why what fired on it does not count as catching it."""
    if not heldout:
        return (
            "\n## 4. The held-out fault\n\nNo finding of any kind was raised on the "
            "cooling tower run. No rule in this project references a tower point, a "
            "tower approach temperature or the wet-bulb temperature, and no failure "
            "mode is configured for the tower, so the rule library was silent exactly "
            "as designed -- and nothing else picked it up either.\n"
        )
    rows = [
        [
            entry.asset_id, entry.source.replace("_", " "), f"`{entry.fault_id}`",
            f"{entry.first_seen:%Y-%m-%d}", str(entry.active_days),
            ("none -- fires only on the faulted run"
             if entry.calendar_twin is None
             else f"**{entry.calendar_twin:%Y-%m-%d}**, same day of the year"),
        ]
        for entry in heldout
    ]
    attributable = [e for e in heldout if e.attributable]
    rules = [e for e in heldout if e.source == "rule"]
    verdict = (
        f"{len(attributable)} of {len(heldout)} findings on this run have no "
        f"fault-free twin, so they are the only ones the tower fault can be credited "
        f"for."
        if attributable else
        "**Every finding on this run has a fault-free twin, so the tower fouling was "
        "not detected.** What fired is the same artefact that fires on a run with no "
        "fault in it at all, on the same day of the year, on the same machines. The "
        "honest reading is not that the degradation layer caught a fault the rules "
        "could not; it is that the degradation layer was already saying this before "
        "the tower fouled."
    )
    return f"""
## 4. The held-out fault

Cooling tower fouling is held out on purpose. No rule in this project references a
cooling tower point, a tower approach temperature or the wet-bulb temperature, and no
failure mode is configured for the tower. It is excluded from every figure above --
scoring it as a missed detection would charge the rule library for a fault it was
deliberately never given, and scoring it as fault-free would credit the chillers for
staying quiet while their condenser water got warmer -- and it is reported here
instead.

**{len(rules)} rule firings.** The rule library was silent on it, which is the
result that was designed for.

Something did fire, from the degradation layer, and the obvious reading of that is
that the trending caught what the rules could not. The obvious reading is testable.
Every synthesised run reads the same 2018 source window shifted by a whole number of
years, so a detection driven by the weather lands on the same day of the year in every
run and a detection driven by the injected fault does not. Each finding below is
therefore checked against the fault-free runs for the same machine, the same channel
and the same calendar day.

{table(["machine", "detector", "channel", "first raised", "active days",
        "same finding on a fault-free run?"], rows)}

{verdict}
"""


def _section_calibration(
    calibrations: list[Calibration], rollups: list[CoverageRollUp],
    unscoreable: list[tuple[str, int, str]], total_estimates: int,
) -> str:
    """Interval coverage. The number this section reports is bad and it is reported."""
    matched = next((r for r in rollups if r.label.startswith("matched mode, against the a")), None)
    crossing = next((r for r in rollups if r.label.startswith("any mode") and "crossing" in r.label), None)
    overall = next((r for r in rollups if r.label.startswith("any mode") and "answer" in r.label), None)

    roll_rows = [
        [
            r.label, f"{r.series}", f"{r.bounded:,}", f"{r.covered:,}",
            f"**{pct(r.coverage)}**", f"{r.late:,}", f"{r.early:,}", f"{r.unbounded:,}",
        ]
        for r in rollups
    ]
    series_rows = []
    for c in sorted(calibrations, key=lambda c: (not c.matched, c.scenario_id, c.mode_id)):
        reach = c.reach
        series_rows.append([
            f"`{c.scenario_id}`", c.asset_id, f"`{c.mode_id}`",
            "**yes**" if c.matched else "no",
            c.reference, f"{c.target}",
            f"{c.in_horizon}", f"{c.bounded}", f"{c.covered}",
            f"**{pct(c.coverage, 0)}**", f"{c.late}", f"{c.early}",
            "n/a" if reach is None else pct(reach.fraction_of_threshold, 0),
        ])

    groups, scoreable = unscoreable
    late_total = overall.late if overall else 0
    early_total = overall.early if overall else 0
    on_clean = next((n for k, n, _ in groups if "fault-free" in k), 0)
    unscoreable_rows = [[f"{n:,}", key, why] for key, n, why in groups]
    excluded_total = sum(n for _k, n, _w in groups)

    return f"""
## 5. Remaining-life interval calibration

A P10-to-P90 band is a promise: the truth should fall inside it about **80%** of the
time. Wider than that and the band is too vague to plan around; narrower and the number
on the screen is not the number the mathematics computed. Neither failure is visible from
one prediction, or from watching a band narrow. It only shows up by counting.

**It does not come out at 80%. It comes out at {pct(overall.coverage) if overall else "n/a"}
against the answer key's failure date, and {pct(matched.coverage) if matched else "n/a"} on
the two series where the mode being scored is the mode that names the injected fault.**
That is reported here because a calibration section that only appeared when the answer was
flattering would be worth nothing, and because the shape of the failure turns out to be
more informative than the headline.

### Coverage, pooled four ways

{table(["population", "series", "estimates with both ends bounded", "covered",
        "coverage", "missed LATE", "missed EARLY", "one end unbounded"],
       roll_rows, align="lrrrrrrr")}

**The misses split into two distinct populations, and the split is the finding.** Scored
against the answer key across every mode, {late_total:,} of {late_total + early_total:,}
misses put the failure LATER than it turned out to be and {early_total:,} put it earlier.
But on the {matched.bounded if matched else 0} matched estimates -- the ones where the mode
being scored is the mode that names the injected fault -- the direction is uniform:
{matched.late if matched else 0} late and {matched.early if matched else 0} early. The same
holds against the indicator's own crossing: {crossing.late if crossing else 0} late,
{crossing.early if crossing else 0} early.

The early misses come from somewhere specific. They are modes whose indicator had ALREADY
crossed its own failure threshold before the answer key's terminal severity arrived, so the
model correctly reports zero days remaining while the answer key still has days left to run.
That is not the model being optimistic; it is the same threshold-versus-terminal-severity
mismatch as the late misses, seen from the other side. **Where the model is genuinely wrong
it is wrong late**, which is the dangerous direction for a maintenance system -- it tells a
planner they have time they do not have.

### Per series, with the number that changes how to read it

{table(["run", "machine", "mode", "names the injected fault", "failure date used",
        "target", "estimates in horizon", "bounded", "covered", "coverage",
        "late", "early", "how far the indicator got toward its own threshold"],
       series_rows, align="llllllrrrrrrr")}

The rightmost column is the one that separates two very different problems.

**On the two matched series the indicator never got near its own failure threshold.** The
coil valve leak reached 57% of the way there and the condenser fouling reached 16%, over
runs the answer key calls failures. So when the model says the crossing is two hundred
days off while the answer key's terminal severity arrives in nineteen, the model is not
obviously wrong -- it is answering the question it was built to answer, which is when the
indicator will reach a threshold that has a physical justification recorded next to it.
The answer key's date is a different event: the last rung of the measured severity ladder.
**Most of the 0% on the matched population is those two events being weeks apart, not the
band being miscalibrated.**

**Where the model's own event did happen, the band still misses, and still late.** The
efficiency indicator on the fouling run crossed its threshold on its own, and there the
coverage against that crossing is {pct(crossing.coverage) if crossing else "n/a"} over
{crossing.bounded if crossing else 0} bounded estimates. Two days before the indicator
actually crossed, the published median was still nearly ten times the true remaining life.
**That is a genuine calibration failure and it is not explained away by the threshold.** It
rests on {crossing.bounded if crossing else 0} estimates, which is a small sample and is
stated as one.

The likely mechanism, stated as a hypothesis rather than a result because this harness does
not test it: the drift rate is fitted over every post-onset daily increment with equal
weight, so a fault whose rate rises late in its life is projected forward at its average
rate rather than its current one, and the average is lower. Nothing here isolates that from
the alternatives, and the fix belongs with the degradation model.

### Estimates that cannot be calibrated at all

The platform published {total_estimates:,} remaining-life estimates. **{scoreable:,} of them
are scoreable against the answer key** and {excluded_total:,} are not; the two add to
{scoreable + excluded_total:,}, which is the whole population, because every estimate falls
into exactly one group below. Reconciling that is not pedantry -- a coverage figure whose
denominator cannot be tied back to what the system actually published is not a measurement,
and an earlier version of this table did not close.

{table(["estimates", "group", "why they cannot be scored"], unscoreable_rows,
       align="rll")}

One of those rows belongs beside section 1. **{on_clean:,} estimates were published on a
machine with no fault injected into it** -- the remaining-life layer naming a failure date
for a chiller that was working. That is the same false positive section 1 attributes to the
efficiency channel, followed one layer downstream, and it is the clearest illustration of
why the false-alarm rate is the first number in this document rather than the last.
"""


def _section_alpha_lambda(
    rollup: list[AlphaLambdaRollUp],
    matched_rollup: list[AlphaLambdaRollUp],
    points: list[AlphaLambdaPoint],
    figure: Path | None,
) -> str:
    """The prognostics accuracy cone, as a table and a figure."""
    rows = []
    for entry, matched in zip(rollup, matched_rollup, strict=True):
        rows.append([
            f"{entry.lam:.1f}",
            f"{matched.within}/{matched.n}" if matched.n else "-",
            f"{entry.within}/{entry.n}" if entry.n else "-",
            pct(entry.hit_rate, 0) if entry.n else "-",
            f"{entry.band_hits}/{entry.n}" if entry.n else "-",
            (f"{entry.median_relative_error * 100:+.0f}%"
             if entry.median_relative_error is not None else "-"),
        ])
    total = len(points)
    hits = sum(1 for p in points if p.within)
    matched_points = [p for p in points if p.matched]
    matched_hits = sum(1 for p in matched_points if p.within)
    link = (
        f"\n![Alpha-lambda accuracy]({figure.relative_to(REPO_ROOT).as_posix()})\n"
        if figure is not None else ""
    )
    return f"""
## 6. Alpha-lambda accuracy

The standard prognostics accuracy question, and the reason it is a cone rather than a
tolerance: is the published median within {ALPHA * 100:.0f}% of the true remaining life,
checked at each fraction of the way from injection to terminal severity. {ALPHA * 100:.0f}%
of ninety days is eighteen days of slack; {ALPHA * 100:.0f}% of five days is one. So the
acceptable region closes on zero as the end approaches, and a prediction can pass early and
fail late without the model having changed. That is the property the metric exists to expose.

The fraction 1.0 is left out on purpose: at the failure date the true remaining life is
zero, so the accepted band has zero width and every prediction fails by construction. That
is arithmetic, not a result.

**{matched_hits} of {len(matched_points)} checks pass on the series that name the injected
fault, and {hits} of {total} across every series scored.**

{table(["fraction of life elapsed", f"within {ALPHA * 100:.0f}%, matched series",
        f"within {ALPHA * 100:.0f}%, all series", "hit rate, all series",
        "P10-P90 contained the truth", "median relative error of P50"],
       rows, align="rrrrrr")}

**The early rows are empty by design, not by omission.** The remaining-life layer refuses to
publish anything until the changepoint detector has confirmed degradation, and on these runs
that confirmation lands between a third and two-thirds of the way through the fault's life.
So there is nothing to check at 0.1 or 0.2: the system was declining to answer, which
section 3 counts as detection latency and this section cannot score at all. An accuracy
metric that filled those rows in would be scoring predictions the platform never made.

The last column is the diagnosis, and it changes sign. Early in the measurable range the
median error is large and positive -- the prediction is long. Late in the range it goes to
-100%, which is one specific thing: the indicator has already crossed its own threshold, so
the model reports zero days remaining while the answer key still has a few days to run. Both
directions come from the same place, which is that the threshold and the terminal severity
are different events. What the metric does not show anywhere is a prediction that is merely
imprecise; the errors are structured, not scattered.
{link}
Read the figure rather than the table if you only look at one. The dashed line is the truth
falling to zero, the shaded wedge is the accepted band closing with it, the solid line is
the published median and the vertical bars are P10 to P90. An upward triangle marks an
estimate where the model declined to bound the upper end at all, which is an answer and is
drawn rather than omitted.

Two things to expect when you open it. On the two panels that name the injected fault, the
accepted wedge is too thin to see: the predictions run into the hundreds of days while the
truth is around ten, and at the scale the predictions force, the wedge collapses onto the
axis. That is the result, not a plotting defect. And on the bypass panels the median sits
flat on zero, which is the already-crossed case described above -- the indicator passed its
threshold early in the run and the model has been saying "no life left" ever since.
"""


def _section_fault_class(outcomes: list[ClassOutcome]) -> str:
    """The sensor-versus-equipment confusion matrix, and the guessing baseline."""
    matrix = class_matrix(outcomes)
    commonest, majority_hits, majority_total = majority_baseline(outcomes)
    scored = [o for o in outcomes if o.scoreable and o.truth is not None]
    correct = sum(1 for o in scored if o.correct)
    misses = [o for o in scored if o.correct is False]

    header = ["true class \\ said"] + [f"**{c}**" for c in CLASSES]
    rows = []
    for truth in CLASSES:
        if not any(o.truth == truth for o in scored):
            continue
        row = [f"**{truth}**"]
        for predicted in CLASSES:
            n = matrix.get((truth, predicted), 0)
            row.append(f"**{n}**" if n and truth == predicted else str(n))
        rows.append(row)

    detail_rows = [
        [
            f"`{o.scenario_id}`", o.asset_id,
            f"`{o.injected_fault}`" if o.injected_fault else "none injected",
            o.truth or "-", f"**{o.predicted}**", o.confidence,
            o.subject or "-", f"{o.violated}/{o.relations}",
            "yes" if o.degrading else "no",
            ("held out" if o.held_out else
             ("correct" if o.correct else ("WRONG" if o.correct is False else "-"))),
        ]
        for o in outcomes
    ]

    healthy = [
        o for o in outcomes
        if o.truth is None and o.skipped_reason.startswith("fault-free")
    ]
    healthy_rows = [
        [f"`{o.scenario_id}`", o.asset_id, f"**{o.predicted}**",
         f"{o.violated}/{o.relations}", "yes" if o.degrading else "no"]
        for o in healthy
    ]
    wrongly_faulted = [o for o in healthy if o.predicted != "ambiguous"]

    air = [o for o in scored if o.asset_id.startswith("ahu")]
    water = [o for o in scored if o.asset_id.startswith("chiller")]
    air_relations = max((o.relations for o in air), default=0)
    water_relations = max((o.relations for o in water), default=0)
    miss_note = "\n\n".join(
        f"- **`{o.scenario_id}` on {o.asset_id}** had true class `{o.truth}` and came out "
        f"`{o.predicted}`, blaming `{o.subject}`, with {o.violated} of the machine's "
        f"{o.relations} relations violated. The classifier's own reasoning: {o.reason}."
        for o in misses
    )

    return f"""
## 7. Sensor versus equipment

A supply air temperature above its setpoint is produced by a coil that cannot cool and by
a thermometer reading high, and from the symptom alone the two are identical. Getting them
the wrong way round dispatches a technician with a wrench to a fault that needs a
calibration kit, or a calibration technician to a machine that is genuinely failing. In
this project's own intervention library the two responses to that one symptom differ by
more than three times in cost, so the discrimination is worth money and not only tidiness.

**{correct} of {len(scored)} injected faults were classified correctly.** Before reading
that as a result, read the next number: a classifier that ignored the data and always
answered `{commonest}` would score {majority_hits} of {majority_total}. What makes the
figure worth having is not the total, it is which cases are in it -- the drifting
thermometer and the jammed damper are exactly the two a majority guess gets wrong, and
both are right, including which physical part to blame.

{table(header, rows, align="l" + "r" * len(CLASSES))}

### The miss, and what it says about the relation set

{miss_note if miss_note else "There were none."}

The pattern behind that is worth more than the score. This test works by asking whether one
sensor reading consistently wrong would make every violated relation hold again, and it can
only answer no if the suspect appears in enough relations to be contradicted. **The air
handler contributes up to {air_relations} relations; a chiller contributes up to
{water_relations}.** On a chiller, electrical power participates in two of those three, so
once a fully developed fault has pushed two relations out at once, a single bias on the
power meter accounts for both and there is nothing left to falsify it with. The reasoning
above says exactly that in the classifier's own words: 99 percent of the violation
reconciled, across the two relations that point appears in.

This is the same falsifiability problem checkpoint 5.4 hit on the air side and solved by
adding the condition-normalised baselines as extra relations, which took supply air
temperature from one relation to three. The chiller never received that treatment. So the
honest reading of this section is not that the discrimination works; it is that **the
discrimination works where the relation set is rich enough to falsify a suspect, and the
count of relations is the thing to look at.** Adding chiller baselines is a
configuration change, not a code change, and it is in `ROADMAP.md`.

### Every classification, individually

{table(["run", "machine", "injected fault", "true class", "said", "confidence",
        "subject named", "relations violated", "degrading", "verdict"],
       detail_rows)}

### What it says when nothing is wrong

The classifier has no "healthy" verdict; it returns one of four classes whenever it is
asked. So it is worth knowing what it answers on the fault-free runs, and the answer is not
uniform:

{table(["run", "machine", "said", "relations violated", "degrading"], healthy_rows,
       align="llrrr")}

{
    f"**{len(wrongly_faulted)} of {len(healthy)} healthy machines were given a fault "
    f"class**, and in each case with zero relations violated -- the verdict comes entirely "
    f"from the degradation flag, which on those machines is the false positive section 1 "
    f"attributes to the efficiency channel. This is that same defect surfacing a third "
    f"time, now as a diagnosis. The two machines with no degradation flag came out "
    f"`ambiguous`, which is the closest thing this taxonomy has to saying nothing is wrong."
    if wrongly_faulted else
    "Every healthy machine came out `ambiguous`, which is the closest thing this taxonomy "
    "has to saying nothing is wrong."
}

### The window this is scored over, and how it was chosen

Each machine is classified over **the last 28 days of its run**, against the three-week
commissioning window at that run's start as the healthy reference.

The window was chosen on operational grounds and not by which window scored best, and the
distinction matters because they are not the same window. In production this classifier
runs on a window ending now, which is what "the most recent 28 days" reproduces, and 28
matches the window the advisory layer already fits its health slope over, so the project
has one notion of "recently" rather than two. A longer window covering the whole
post-injection stretch was tried. It is measurably worse on the air handler -- across three
months reaching from winter into summer the cooling coil valve's average position drifts far
enough from its command that a leaking valve is reported as an actuator refusing orders --
and measurably better on the chiller. Choosing per equipment class would be fitting the
harness to the answer key, so one rule is applied and the run it gets wrong is reported as
wrong.

The reference is each run's own commissioning window because that exists for every run. A
fault-free run at the same time of year is the stronger choice and is what checkpoint 5.4
used, but two of the air-handler runs sit in late winter and early spring and the only
fault-free air-handler run is a summer one. The check that the substitution does not change
the answer is the coil-leak run, the one case where both references cover the same 28 days:
both return `equipment`.

This window is deliberately NOT restricted to severity level 1, which makes these figures
easier than the detection figures in section 2. The classifier works by asking which
relations have stopped holding; at level 1 on several of these runs nothing has visibly
stopped holding yet, so asking it to name a fault it cannot see measures the detector again
rather than the classifier. Detection is scored where detection is hard. Attribution is
scored where attribution is asked.
"""


def _section_suppression(cases: list[SuppressionCase]) -> str:
    """Whether the demoted advisory was demoted for a true reason."""
    rows = [
        [
            case.label,
            f"`{case.scenario_id}`",
            f"{case.window[0]:%Y-%m-%d} to {case.window[1]:%Y-%m-%d}",
            "composed" if case.composed else "real",
            str(case.open_faults),
            str(len(case.demotions)),
            f"**{case.verdict}**",
            "yes" if case.ordering_holds else "**NO**",
        ]
        for case in cases
    ]
    refusals = [c for c in cases if c.verdict == "CORRECT REFUSAL"]
    wrong = [c for c in cases if c.verdict == "WRONG ATTRIBUTION"]
    detail = "\n".join(
        f"- **{case.label}** — {case.reason}." for case in cases
    )
    return f"""
## 8. Cross-asset suppression correctness

The cross-asset layer marks a downstream symptom consequential when an upstream machine has
an open fault whose mechanism could produce it, and then ranks that advisory below the
advisory it blames. That is an inference, and the whole design of the layer -- demote,
never hide -- is a bet on the inference being wrong sometimes. This section checks whether
it was.

**What the answer key can settle, and what it cannot.** It can say what fault was injected
into which machine, so it can FALSIFY a consequential label: if a fault was injected
directly into the machine carrying the symptom, that symptom had a cause of its own and did
not need an upstream one. It cannot confirm a cross-asset link in the positive direction,
and the reason is in the source data. The two LBNL systems are independent simulations --
the air handler's chilled water comes from a boundary condition inside its own simulation,
not from this chiller -- so no run in this dataset contains a genuine chiller-caused air
handler symptom for the layer to get right. That absence is why checkpoint 6.1 had to
compose its target scenario, and it is stated rather than worked around.

{table(["situation", "run", "window", "data", "open faults", "demoted", "verdict",
        "demoted advisory ranked below its cause"], rows)}

{detail}

**{len(refusals)} correct refusals and {len(wrong)} wrong attribution.** The refusals are
not filler. In both of those windows an upstream machine has an open fault and the timing
overlaps, so topology and concurrency both permit a link; the plausibility map declines
anyway, because the open upstream faults there cost power rather than capacity and cannot
warm the water the coil is fed with. A demotion layer that never declines to demote is
indistinguishable from one that demotes everything, so the negative cases are what make the
positive one mean anything.

**And the positive one is wrong.** On the composed window the air handler's saturated
cooling valve is blamed on the chiller's condenser fouling two hops upstream -- and the
answer key says the fault injected into that run was a supply air temperature sensor drift,
injected directly into the air handler. The symptom needed no upstream explanation. Section
7 reaches the same conclusion independently: the classifier names that machine's fault a
sensor fault, on the machine's own evidence, with no knowledge of the answer key.

This is the case the demote-rather-than-hide decision was made for. The advisory is ranked
below its supposed cause, and it is still on the operator's screen, carrying the sensor
badge and the reconciliation evidence that contradicts the attribution. Had the layer
suppressed it instead, a real fault would have been removed from the queue on the strength
of an inference that was wrong, and nothing on the screen would have said so. The ordering
mechanism is correct in all three situations; the inference it is applied to is wrong in
the one case this dataset can produce.
"""


def _section_method(
    severity_windows: dict[str, SeverityWindow],
    grid_check: list[tuple[str, int, int]],
    sweep: Sweep,
) -> str:
    window_rows = [
        [
            f"`{scenario_id}`",
            str(window.n_levels) if window.n_levels else "-",
            f"{window.t_from:%Y-%m-%d}" if window.t_from else "-",
            f"{window.t_to:%Y-%m-%d}" if window.t_to else "-",
            f"{window.days:.1f}" if window.scored else "-",
            window.reason,
        ]
        for scenario_id, window in sorted(severity_windows.items())
    ]
    mismatches = [c for c in grid_check if c[1] != c[2]]
    grid_rows = [
        [f"`{scenario_id}`", f"{rebuilt:,}", f"{actual:,}",
         "match" if rebuilt == actual else "**MISMATCH**"]
        for scenario_id, rebuilt, actual in sorted(grid_check)
    ]
    rules_only = ", ".join(f"`{s}`" for s in sorted(RULES_ONLY))

    return f"""
## Method, and what these numbers do not cover

### How the severity-1 boundary was found

The simulator builds a run by mixing consecutive measured-severity files in
proportion, driven by a progress curve seeded from the scenario's own integer seed.
Progress 0 sits on the fault-free file and progress 1 on the worst rung, so
multiplying progress by the number of rungs gives the position on the severity ladder
at every instant. The severity-1 window closes at the first instant that position
reaches 1.0. A fault with one measured rung never leaves level 1 and its window runs
to failure; a step fault arrives at the top rung at injection and has no level-1
window at all.

{table(["run", "rungs", "level 1 from", "level 1 to", "days", "boundary"],
       window_rows)}

The reconstruction rebuilds the timestamp grid the curve was originally evaluated on
from the run's start and span, rather than re-parsing 21 source CSVs to recover
timestamps that three integers already determine. That makes the grid length a load
bearing assumption, so it is checked against the database rather than assumed:
{"every run matches." if not mismatches else f"**{len(mismatches)} run(s) do not match.**"}

{table(["run", "rebuilt grid", "readings in the database", "check"], grid_rows,
       align="lrrl")}

### What is not scored here

- **Data-quality advisories are not counted in either direction.** The quality layer
  raises its own findings -- a sensor stuck at one value, a reading outside its
  physical envelope, a point gone silent. Those are correct about a different
  question. The answer key holds no instrument-failure labels to score them against,
  and folding them into the false-alarm rate would charge the fault detector for
  findings that were right.
- **{rules_only} is scored for rule firings only.** The health layer runs over the
  eight synthesised scenario windows, so the LBNL reference year contributes no
  confirmed-degradation detections. Adding it would mean declaring a commissioning
  window inside 2018 and extending the run list, which changes what the health layer
  has computed rather than measuring it.
- **Coupled machines are excluded, not assumed healthy.** The chiller data is a
  whole-plant simulation. When one chiller is fouled the other two see a different
  loop around them, so they are neither faulted nor assertably healthy, and their
  asset-days are removed from both sides of the matrix.
- **The sample is small and every proportion here rests on single-digit event
  counts.** {len(sweep.findings)} findings and a handful of injected faults. The
  asset-day denominators run to thousands, which makes the confusion matrix
  well-conditioned, but the per-fault table has one row per fault and one missed
  fault moves it visibly. These are measurements on one building with two equipment
  classes, not a benchmark result.
"""
