"""Render VALIDATION.md from computed metrics. No number in this file is a literal.

The document is generated on every run and overwritten in place. That is a rule with
a reason behind it: a validation document with hand-written numbers in it decays
silently, and the moment one figure in it is stale the whole document is worthless
because a reader cannot tell which one. Every quantity below arrives as an argument.
The prose is fixed and the numbers are not, so a regression shows up as a changed
number under unchanged prose rather than as a document nobody dares regenerate.
"""

from __future__ import annotations

from datetime import datetime

from validation.detect import RULES_ONLY, Sweep
from validation.groundtruth import FaultEvent, ScenarioLabel, SeverityWindow
from validation.metrics import (
    EXCLUDED_SCENARIOS,
    Confusion,
    EventOutcome,
    FalseAlarms,
    FalsePositiveSource,
    HeldOut,
    LeadSummary,
    LeadTime,
)

HEADER = """# Validation

> **Generated by `validation/harness.py` on {generated}. Do not edit by hand.**
> Every number in this document is recomputed from the database and the answer key on
> each run and the file is overwritten in place. Regenerate with `make validate`.

The labels these results are scored against were not created by this project. The
fault signatures come from the LBNL Fault Detection and Diagnostics Datasets, a public
release produced by a consortium of LBNL, PNNL, NREL, ORNL and Drexel, in which each
fault is simulated at several measured severities alongside a fault-free reference
run. What this project synthesised is the trajectory BETWEEN those measured
severities, because no public run-to-failure dataset exists for building HVAC
equipment. The answer key therefore holds two kinds of fact: which fault was injected
into which machine, which is LBNL's, and when it passed each severity rung, which is
this project's.

The separation is enforced by the database rather than by discipline. Every layer that
detects, scores, baselines, predicts or diagnoses connects as a role with no access
whatsoever to schema `groundtruth` -- not restricted access, none -- and the answer key
is opened by exactly one module, `validation/groundtruth.py`, under a different
credential. No detector in this project can have seen the label it is scored against.

**What was evaluated.** {windows} windows spanning {span_from} to {span_to}.
{observed:,} asset-days hold readings; of those, {scored:,} are days on which at least
one detector was willing to judge the machine, and only those can appear in a table
below. {findings} findings were raised across every detector.

The gap between those two counts is not rounding. The rules decline to evaluate an
air handler while the building is unoccupied, and decline to evaluate a chiller that
is not running, for an hour after it starts, and at any instant below a minimum load.
One of the three chillers in this plant runs about one percent of the year. Counting
its idle days as days it was correctly found healthy would have added hundreds of free
true negatives to every table below and quietly divided the false-alarm rate.
"""

WHY_FALSE_ALARMS = """
## 1. False alarms per asset-day

**This is the first number in this document on purpose.** Automated fault detection in
buildings does not usually fail by missing faults. It fails by crying wolf: the
detection works, the operator is interrupted several times a day by findings that turn
out to be a warm afternoon or a scheduled setpoint change, and within a month nobody
opens the screen again. A system with perfect recall and one spurious finding per
machine per day has trained the person it was bought for to ignore it, and is worth
less than no system at all. So the rate on equipment that was working comes before any
claim about equipment that was not.

Counted over asset-days labelled healthy: the two synthesised fault-free runs, the
LBNL fault-free reference year, and the pre-injection stretch of every faulted run.
Pre-injection days are ordinary healthy days here, including the three weeks the
baselines are fitted on -- a finding raised while the equipment was still healthy is a
false alarm whatever else was happening that week.

Three counts, because they answer different questions:

- **findings per asset-day** is the headline. A finding is one (machine, fault) pair
  raised once, however many separate episodes it covered -- the unit an operator
  disposes of. Nine afternoons of the same saturated valve is one finding, not nine.
- **alarm-days** is the share of healthy days with at least one finding standing. It
  is exactly the false-positive count in section 2's confusion matrix, so the two
  sections cannot disagree.
- **episodes** is the raw count of sustained stretches, carried only so these figures
  line up against the per-rule tables produced in checkpoints 3.3 and 3.4.
"""

WHY_SEVERITY_ONE = """
## 2. Detection at severity level 1

### Why every accuracy figure here is restricted to level 1

LBNL publishes each fault at several measured severities. Condenser fouling comes at
95% and 65% of heat transfer retained; bypass leakage at 25%, 50% and 75%; the damper
stuck at 10%, 25% and 75% open. **Detecting the severe end of that range is not
evidence that a fault detection system works.** A condenser down to 65% of its heat
transfer moves the approach temperature and the kilowatts per ton so far outside
anything weather can explain that a fixed threshold set by hand would catch it. The
severe cases are the ones any system catches, and an accuracy figure computed over a
whole trajectory is dominated by them.

Severity level 1 is the opposite case. It is the mildest condition LBNL measured for
that fault -- a valve leaking slightly, 5% of heat transfer lost -- and its effect on
every signal is of the same order as the effect of the outdoor air temperature being a
few degrees higher than yesterday. Separating it from normal operation is the whole
problem. It is also the only case where a warning is worth anything, because by the
time the fault reaches its terminal severity the energy has already been spent.

So the severity-1 window of each run is reconstructed by replaying the same seeded
trajectory the simulator built the run from, and it closes the moment the trajectory
reaches the SECOND measured rung. Every asset-day after that is excluded from the
figures below rather than counted as an easy win.

### What counts as a detection

A detection is a claim about a MACHINE on a DAY: the platform told an operator
something was wrong with this unit today. Any of the nine physics-derived rules, or
any failure mode whose degradation the changepoint detector confirmed, counts.

Two things follow, and both cut against the numbers rather than for them. The rule
firings are re-run from the measurements here rather than read from a table, because
nothing persists them. The degradation detections are also re-run, for a subtler
reason: `app.health_state` stores the changepoint detector's ESTIMATED onset -- the
retrospective "this began on the 3rd" -- and an operator learned nothing on the 3rd.
They learned when the cumulative-sum statistic crossed its decision interval, which is
days later and is written down nowhere. Scoring against the estimated onset would
credit this system with warning it never gave, so the health layer is recomputed and
the confirmation instant is used.

The claim is also deliberately generous in one direction, stated plainly: it is
asset-level, so a run is credited when ANY channel fires on the faulted machine, not
only when the correct fault is named. During condenser fouling the efficiency-loss mode
firing is physically the same fault seen from another angle and crediting it is fair;
during sensor drift, a mode firing for an unrelated reason would also be credited and
that is not. Whether the right fault was NAMED is a separate question and these figures
do not answer it.
"""

WHY_LEAD_TIME = """
## 3. Lead time

The gap between the first warning and the failure is what this system is for.
Detecting a fault the week the equipment stops is a report, not a prediction.

The population is one row per (injected fault, detection channel), not one row per
fault. That is what makes a distribution out of a handful of events: condenser fouling
is caught by the approach-temperature rule, by the kilowatt-per-ton rule, and by two
separate degradation modes, and those warnings arrive on four different days. Quoting
only the earliest would describe a system that always warns as early as its luckiest
detector. The **tenth percentile is the number to read** -- nine warnings in ten
arrived at least this far ahead -- and the median is the typical case.

Failure here means the injected fault reaching its terminal severity, which is the
answer key's `t_failure`. That is not the same event as the indicator crossing the
physically justified threshold the remaining-life model predicts, and the two dates can
differ by weeks -- an important distinction, because it means a lead time measured here
and a remaining-life error are answers to two different questions.
"""


def table(headers: list[str], rows: list[list[str]], align: str = "") -> str:
    """A GitHub-flavoured markdown table. `align` is one of l, r, c per column."""
    align = align or "l" * len(headers)
    rule = {"l": ":---", "r": "---:", "c": ":---:"}
    out = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(rule[a] for a in align) + " |",
    ]
    out += ["| " + " | ".join(row) + " |" for row in rows]
    return "\n".join(out)


def pct(value: float | None, digits: int = 1) -> str:
    return "n/a" if value is None else f"{value * 100:.{digits}f}%"


def num(value: float | None, digits: int = 1) -> str:
    return "n/a" if value is None else f"{value:.{digits}f}"


def render(
    generated: datetime,
    labels: dict[str, ScenarioLabel],
    events: list[FaultEvent],
    severity_windows: dict[str, SeverityWindow],
    sweep: Sweep,
    span: tuple[str, str],
    alarms: list[FalseAlarms],
    matrix: Confusion,
    outcomes: list[EventOutcome],
    leads: list[LeadTime],
    summaries: list[LeadSummary],
    late: list[tuple[str, str, str, float]],
    heldout: list[HeldOut],
    sources: list[FalsePositiveSource],
    grid_check: list[tuple[str, int, int]],
) -> str:
    """The whole document."""
    parts = [
        HEADER.format(
            generated=generated.strftime("%Y-%m-%d %H:%M:%S %Z"),
            windows=len(sweep.scored),
            observed=sweep.observed_asset_days,
            scored=sweep.scored_asset_days,
            findings=len(sweep.findings),
            span_from=span[0],
            span_to=span[1],
        ),
        _section_false_alarms(alarms),
        _section_detection(
            matrix, outcomes, severity_windows, labels, events, sources, sweep
        ),
        _section_lead_time(summaries, leads, late),
        _section_held_out(heldout),
        _section_method(severity_windows, grid_check, sweep),
    ]
    return "\n".join(parts).rstrip() + "\n"


def _section_false_alarms(alarms: list[FalseAlarms]) -> str:
    rows = []
    total_days = total_findings = total_alarm_days = total_episodes = 0
    for entry in sorted(alarms, key=lambda a: -a.asset_days):
        rows.append([
            f"`{entry.scenario_id}`",
            f"{entry.asset_days:,}",
            str(entry.findings),
            f"**{entry.findings_per_asset_day:.4f}**",
            f"{entry.alarm_days:,} ({pct(entry.alarm_day_fraction)})",
            str(entry.episodes),
            entry.detectors,
        ])
        total_days += entry.asset_days
        total_findings += entry.findings
        total_alarm_days += entry.alarm_days
        total_episodes += entry.episodes
    rate = total_findings / total_days if total_days else 0.0
    rows.append([
        "**ALL HEALTHY ASSET-DAYS**",
        f"**{total_days:,}**",
        f"**{total_findings}**",
        f"**{rate:.4f}**",
        f"**{total_alarm_days:,}**",
        f"**{total_episodes}**",
        "",
    ])
    body = table(
        ["run", "healthy asset-days", "findings", "findings per asset-day",
         "alarm-days", "episodes", "detectors evaluated"],
        rows,
        align="lrrrrrl",
    )
    headline = (
        f"\n**{rate:.4f} findings per healthy asset-day** across {total_days:,} "
        f"asset-days of equipment that was working: one finding every "
        f"{1.0 / rate:,.0f} asset-days.\n"
        if rate > 0 else
        f"\n**Zero findings across {total_days:,} healthy asset-days.**\n"
    )
    return WHY_FALSE_ALARMS + "\n" + body + "\n" + headline


def _section_detection(
    matrix: Confusion,
    outcomes: list[EventOutcome],
    severity_windows: dict[str, SeverityWindow],
    labels: dict[str, ScenarioLabel],
    events: list[FaultEvent],
    sources: list[FalsePositiveSource],
    sweep: Sweep,
) -> str:
    scored = matrix.tp + matrix.fp + matrix.fn + matrix.tn
    unlabelled = sweep.scored_asset_days - scored
    confusion_table = table(
        ["", "platform flagged the machine", "platform said nothing"],
        [
            ["**fault present, at level 1**", f"**{matrix.tp:,}** true positive",
             f"{matrix.fn:,} false negative"],
            ["**equipment healthy**", f"{matrix.fp:,} false positive",
             f"{matrix.tn:,} true negative"],
        ],
        align="lrr",
    )
    headline = table(
        ["metric", "value", "reading"],
        [
            ["**precision**", f"**{pct(matrix.precision, 1)}**",
             "of the days we raised something, this share had a real fault"],
            ["**recall**", f"**{pct(matrix.recall, 1)}**",
             "of the days a mild fault was present, this share was flagged"],
            ["**F1**", f"**{num(matrix.f1, 3)}**", "harmonic mean of the two"],
        ],
        align="lrl",
    )

    event_rows = []
    for outcome in outcomes:
        event_rows.append([
            f"`{outcome.scenario_id}`",
            outcome.asset_id,
            f"`{outcome.fault_mode}`",
            outcome.mildest_label,
            f"{outcome.window_days:.1f}",
            "**yes**" if outcome.caught else "**NO**",
            num(outcome.days_after_injection) if outcome.caught else "-",
            outcome.first_channel or "-",
            f"{outcome.detected_days}/{outcome.positive_days} ({pct(outcome.coverage, 0)})",
        ])
    event_table = table(
        ["run", "machine", "injected fault", "LBNL's mildest measured case",
         "level-1 window, days", "caught at level 1", "days to first warning",
         "which channel fired first", "level-1 days flagged"],
        event_rows,
        align="lllllcrlr",
    )

    excluded_rows = []
    for scenario_id, reason in sorted(EXCLUDED_SCENARIOS.items()):
        excluded_rows.append([f"`{scenario_id}`", reason])
    for scenario_id, window in sorted(severity_windows.items()):
        label = labels.get(scenario_id)
        if window.scored or (label is not None and label.is_fault_free):
            continue
        if scenario_id in EXCLUDED_SCENARIOS:
            continue
        excluded_rows.append([f"`{scenario_id}`", window.reason])
    excluded = table(["run", "why it is not in the figures above"], excluded_rows)

    caught = sum(1 for o in outcomes if o.caught)
    return (
        WHY_SEVERITY_ONE
        + f"\n### Confusion over {scored:,} labelled asset-days\n\n"
        + f"A further {unlabelled:,} asset-days were judged by a detector but carry no "
          f"label: the fault was present and had already passed level 1. They appear in "
          f"neither row.\n\n"
        + confusion_table + "\n\n" + headline
        + _false_positive_note(matrix, sources, sweep)
        + f"\n### Per injected fault\n\n{caught} of {len(outcomes)} injected faults "
          f"were caught while still at severity level 1.\n\n"
        + event_table
        + "\n\n### Runs excluded from these figures, and why\n\n"
        + excluded + "\n"
        + f"\n{len(events)} faults are recorded in the answer key in total. The "
          f"held-out one is reported on its own in section 4.\n"
    )


def _false_positive_note(
    matrix: Confusion, sources: list[FalsePositiveSource], sweep: Sweep
) -> str:
    """Where the false positives came from. Precision without this is not usable."""
    if not sources:
        return (
            f"\n### Where the false positives came from\n\nThere were none: not one "
            f"finding stood on a healthy asset-day across all {matrix.tn:,} of them.\n"
        )
    rows = [
        [
            f"`{entry.scenario_id}`", entry.asset_id, f"`{entry.fault_id}`",
            entry.source.replace("_", " "), f"{entry.fp_days:,}",
            pct(entry.fp_days / matrix.fp if matrix.fp else 0.0, 0),
            ("**yes** — " + ", ".join(f"{d:%Y-%m-%d}" for d in entry.calendar_twins)
             if entry.calendar_twins else "no"),
        ]
        for entry in sources
    ]
    total_findings = len(sweep.findings)
    worst = sources[0]
    share = worst.fp_days / matrix.fp if matrix.fp else 0.0
    points = worst.health_points_lost
    return f"""

### Where the false positives came from

{table(["run", "machine", "channel", "detector", "false-positive asset-days",
        "share of all false positives", "same channel, same day of year, another run?"],
       rows, align="llllrrl")}

**{len(sources)} distinct false findings, out of {total_findings} findings raised in
total**, and between them they stood for {matrix.fp} healthy asset-days. Those are the
same result counted two ways and both are worth having: the platform put
{len(sources)} wrong item{"" if len(sources) == 1 else "s"} in front of an operator, and
each then sat on the screen for two months afterwards. Precision is computed per
asset-day, so it is the second framing that drags it to {pct(matrix.precision)}. Counted
as findings instead, {len(sources)} of {total_findings} were raised on a machine with
nothing wrong with it.

`{worst.fault_id}` on `{worst.asset_id}` alone is {pct(share, 0)} of the false-positive
total. Its detail: {worst.detail}. So the whole finding is a confirmed change costing
{points} health point{"" if points == 1 else "s"} out of a hundred -- and the rightmost
column above is the more damning part of it. That channel raises the same finding on the
same machine on the same day of the year across several runs, faulted and fault-free
alike. Every run reads the same 2018 source data shifted by whole years, so a detection
repeating on the same calendar day is responding to something in the weather and load of
that week rather than to the condition of the machine. What exactly, these measurements
do not establish -- the indicator's mean over the fault-free run is within 0.01 of zero,
so it is not a steady seasonal drift, and identifying the mechanism belongs with the
indicator rather than with the harness.

It is a real false positive and it would reach an operator. It would arrive at the bottom
of the queue rather than as an alarm -- {points} health point{"" if points == 1 else "s"}
produces almost no severity and almost no cost of inaction -- which is what the ranking in
the advisory layer is for. But ranking it low is not the same as being right about it, and
this is the clearest defect these measurements expose.
"""


def _section_lead_time(
    summaries: list[LeadSummary],
    leads: list[LeadTime],
    late: list[tuple[str, str, str, float]],
) -> str:
    rows = []
    for entry in summaries:
        bold = entry.fault_mode.startswith("ALL")
        wrap = (lambda s: f"**{s}**") if bold else (lambda s: s)
        rows.append([
            wrap(f"`{entry.fault_mode}`" if not bold else entry.fault_mode),
            wrap(str(entry.n)),
            wrap(f"{entry.median:.1f}"),
            wrap(f"{entry.p10:.1f}"),
            wrap(f"{entry.minimum:.1f}"),
            wrap(f"{entry.maximum:.1f}"),
            wrap(entry.earliest_channel),
        ])
    summary_table = table(
        ["injected fault", "warnings", "median lead, days",
         "10th percentile, days", "worst", "best", "earliest channel"],
        rows,
        align="lrrrrrl",
    )

    detail_rows = [
        [
            f"`{lead.scenario_id}`", lead.asset_id, lead.source.replace("_", " "),
            f"`{lead.fault_id}`", f"{lead.first_seen:%Y-%m-%d}",
            f"{lead.t_failure:%Y-%m-%d}", f"**{lead.lead_days:.1f}**",
        ]
        for lead in leads
    ]
    detail = table(
        ["run", "machine", "detector", "channel", "first warning",
         "terminal severity reached", "lead, days"],
        detail_rows,
        align="llllllr",
    )

    late_note = ""
    if late:
        late_rows = [
            [f"`{scenario}`", asset, f"`{fault}`", f"{delay:.1f}"]
            for scenario, asset, fault, delay in late
        ]
        late_note = (
            "\n### Findings that were not warnings\n\n"
            "Raised only after the injected fault had already reached terminal "
            "severity, so they carry no lead and are excluded from the distribution "
            "above rather than averaged into it.\n\n"
            + table(
                ["run", "machine", "channel", "days after terminal severity"],
                late_rows,
                align="lllr",
            )
            + "\n"
        )

    return (
        WHY_LEAD_TIME
        + "\n" + summary_table
        + "\n\n### Every warning, individually\n\n" + detail + "\n"
        + late_note
    )


def _section_held_out(heldout: list[HeldOut]) -> str:
    """The cooling tower fault, and why what fired on it does not count as catching it."""
    if not heldout:
        return (
            "\n## 4. The held-out fault\n\nNo finding of any kind was raised on the "
            "cooling tower run. No rule in this project references a tower point, a "
            "tower approach temperature or the wet-bulb temperature, and no failure "
            "mode is configured for the tower, so the rule library was silent exactly "
            "as designed -- and nothing else picked it up either.\n"
        )
    rows = [
        [
            entry.asset_id, entry.source.replace("_", " "), f"`{entry.fault_id}`",
            f"{entry.first_seen:%Y-%m-%d}", str(entry.active_days),
            ("none -- fires only on the faulted run"
             if entry.calendar_twin is None
             else f"**{entry.calendar_twin:%Y-%m-%d}**, same day of the year"),
        ]
        for entry in heldout
    ]
    attributable = [e for e in heldout if e.attributable]
    rules = [e for e in heldout if e.source == "rule"]
    verdict = (
        f"{len(attributable)} of {len(heldout)} findings on this run have no "
        f"fault-free twin, so they are the only ones the tower fault can be credited "
        f"for."
        if attributable else
        "**Every finding on this run has a fault-free twin, so the tower fouling was "
        "not detected.** What fired is the same artefact that fires on a run with no "
        "fault in it at all, on the same day of the year, on the same machines. The "
        "honest reading is not that the degradation layer caught a fault the rules "
        "could not; it is that the degradation layer was already saying this before "
        "the tower fouled."
    )
    return f"""
## 4. The held-out fault

Cooling tower fouling is held out on purpose. No rule in this project references a
cooling tower point, a tower approach temperature or the wet-bulb temperature, and no
failure mode is configured for the tower. It is excluded from every figure above --
scoring it as a missed detection would charge the rule library for a fault it was
deliberately never given, and scoring it as fault-free would credit the chillers for
staying quiet while their condenser water got warmer -- and it is reported here
instead.

**{len(rules)} rule firings.** The rule library was silent on it, which is the
result that was designed for.

Something did fire, from the degradation layer, and the obvious reading of that is
that the trending caught what the rules could not. The obvious reading is testable.
Every synthesised run reads the same 2018 source window shifted by a whole number of
years, so a detection driven by the weather lands on the same day of the year in every
run and a detection driven by the injected fault does not. Each finding below is
therefore checked against the fault-free runs for the same machine, the same channel
and the same calendar day.

{table(["machine", "detector", "channel", "first raised", "active days",
        "same finding on a fault-free run?"], rows)}

{verdict}
"""


def _section_method(
    severity_windows: dict[str, SeverityWindow],
    grid_check: list[tuple[str, int, int]],
    sweep: Sweep,
) -> str:
    window_rows = [
        [
            f"`{scenario_id}`",
            str(window.n_levels) if window.n_levels else "-",
            f"{window.t_from:%Y-%m-%d}" if window.t_from else "-",
            f"{window.t_to:%Y-%m-%d}" if window.t_to else "-",
            f"{window.days:.1f}" if window.scored else "-",
            window.reason,
        ]
        for scenario_id, window in sorted(severity_windows.items())
    ]
    mismatches = [c for c in grid_check if c[1] != c[2]]
    grid_rows = [
        [f"`{scenario_id}`", f"{rebuilt:,}", f"{actual:,}",
         "match" if rebuilt == actual else "**MISMATCH**"]
        for scenario_id, rebuilt, actual in sorted(grid_check)
    ]
    rules_only = ", ".join(f"`{s}`" for s in sorted(RULES_ONLY))

    return f"""
## Method, and what these numbers do not cover

### How the severity-1 boundary was found

The simulator builds a run by mixing consecutive measured-severity files in
proportion, driven by a progress curve seeded from the scenario's own integer seed.
Progress 0 sits on the fault-free file and progress 1 on the worst rung, so
multiplying progress by the number of rungs gives the position on the severity ladder
at every instant. The severity-1 window closes at the first instant that position
reaches 1.0. A fault with one measured rung never leaves level 1 and its window runs
to failure; a step fault arrives at the top rung at injection and has no level-1
window at all.

{table(["run", "rungs", "level 1 from", "level 1 to", "days", "boundary"],
       window_rows)}

The reconstruction rebuilds the timestamp grid the curve was originally evaluated on
from the run's start and span, rather than re-parsing 21 source CSVs to recover
timestamps that three integers already determine. That makes the grid length a load
bearing assumption, so it is checked against the database rather than assumed:
{"every run matches." if not mismatches else f"**{len(mismatches)} run(s) do not match.**"}

{table(["run", "rebuilt grid", "readings in the database", "check"], grid_rows,
       align="lrrl")}

### What is not scored here

- **Data-quality advisories are not counted in either direction.** The quality layer
  raises its own findings -- a sensor stuck at one value, a reading outside its
  physical envelope, a point gone silent. Those are correct about a different
  question. The answer key holds no instrument-failure labels to score them against,
  and folding them into the false-alarm rate would charge the fault detector for
  findings that were right.
- **{rules_only} is scored for rule firings only.** The health layer runs over the
  eight synthesised scenario windows, so the LBNL reference year contributes no
  confirmed-degradation detections. Adding it would mean declaring a commissioning
  window inside 2018 and extending the run list, which changes what the health layer
  has computed rather than measuring it.
- **Coupled machines are excluded, not assumed healthy.** The chiller data is a
  whole-plant simulation. When one chiller is fouled the other two see a different
  loop around them, so they are neither faulted nor assertably healthy, and their
  asset-days are removed from both sides of the matrix.
- **The sample is small and every proportion here rests on single-digit event
  counts.** {len(sweep.findings)} findings and a handful of injected faults. The
  asset-day denominators run to thousands, which makes the confusion matrix
  well-conditioned, but the per-fault table has one row per fault and one missed
  fault moves it visibly. These are measurements on one building with two equipment
  classes, not a benchmark result.
"""
